# Generated by Django 2.2.5 on 2019-10-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='customername',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
    ]
