# Generated by Django 2.2.5 on 2019-10-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_update_customername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='author',
        ),
    ]
