# Generated by Django 2.2.5 on 2019-10-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_update_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='customername',
        ),
    ]
