# Generated by Django 2.2.5 on 2019-10-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_update_customername'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='customername',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
