# Generated by Django 2.2.5 on 2019-10-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_update_customername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='customername',
        ),
        migrations.AlterField(
            model_name='update',
            name='givenamount',
            field=models.CharField(max_length=200),
        ),
    ]
