# Generated by Django 2.2.5 on 2019-10-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191020_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='token',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
